### ISSUE TITLE
Consider providing additional detail to the listing at the Umbraco marketplace

### ISSUE THREAD

**Issue by AndyButland** [hfloyd/Dragonfly.Umbraco9#2]
Hi @hfloyd - I noted you'd listed this package on the Umbraco marketplace, so firstly, thanks for taking the time to do that.  I noticed though that we only have the details collected from NuGet for the package... which is fine, but to help it to be found more easily it's possible to provided additional information, as is discussed [here](https://marketplace.umbraco.com/listing).

For example, you can add a category that the package will be shown under, and also provide additional descriptions or "read me" content to better describe what the package does and what benefits developers would get from installing it.

To use this you need to create a file in the root of the project URL you are referencing in the NuGet package - so in this case, at `https://dragonflylibraries.com/umbraco-packages/umbraco-helpers/umbraco-marketplace-dragonfly.umbraco9.json` - and populate it with the additional information in JSON format, as per the documentation linked above.

**Comment by hfloyd** [comment]
@AndyButland - Hi Andy! Thanks for pointing out that my marketplace data isn't loading. Checking it, I see this:
https://dragonflylibraries.com//umbraco-marketplace/?PackageId=Dragonfly.Umbraco9

![image](https://user-images.githubusercontent.com/1252593/223180702-b89cd585-d022-448c-8f71-545860ad6a7b.png)

So, should the "VideoUrl" property have "null" or just be excluded from the feed?

**Comment by AndyButland** [comment]
Yes, looks like it's tripping up on some validation we've added to ensure the video URL added is one we support.  You can certainly omit values for anything you aren't providing, so yes, I'd suggest removing `VideoUrl` from the JSON file.

**Comment by hfloyd** [comment]
_NOTE TO SELF: https://stackoverflow.com/questions/6507889/how-to-ignore-a-property-in-class-if-null-using-json-net_

**Comment by hfloyd** [comment]
@AndyButland - I've got this fixed now. Thanks for the heads-up!
